import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
  return <div className="border-b-[1px] pt-10">
    <div className="flex gap-4">
    <Link href="/" className="text-xl hover:text-gray-500">Home</Link>
    <Link href="/blog" className="text-xl hover:text-gray-500">Blog</Link>
    </div>

  </div>
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4 md:p-0 md:w-[900px] mx-auto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
